### ISSUE TITLE
Add EIP-55 validation

### ISSUE THREAD

**Issue by awoie** [spruceid/siwe-ruby#11]
EIP-55 validation should be added to parsing to avoid interop issues. We should use the new EIP-55 test cases from the siwe repository.

**Comment by q9f** [comment]
The `eth` gem implements EIP-55.

```diff
-      @address = address 
+      @address = Eth::Address.new address
```

* `Eth::Address.new` fails on invalid addresses.
* `Eth::Address.to_s` returns a checksummed address.
