### ISSUE TITLE
Doc examples are wrong.

### ISSUE THREAD

**Issue by pabloruiz55** [spruceid/siwe-ruby#18]
According to the examples one should verify a signature by executing 

```
message = Siwe::Message.from_message "https://example.com wants you to sign in with your Ethereum account:\n0xA712a0AFBFA8656581BfA96352c9EdFc519e9cad\n\n\nURI: https://example.com\nVersion: 1\nChain ID: 1\nNonce: 9WrH24z8zpiYOoBQ\nIssued At: 2022-02-04T15:52:03Z"
    message.validate "aca5e5649a357cee608ecbd1a8455b4143311381636b88a66ec7bcaf64b3a4743ff2c7cc18501a3401e182f79233dc73fc56d01506a6098d5e7e4d881bbb02921c"
```

but Siwe::Message.validate expects 0 arguments and does not actually validate the signed message.
**The correct function to call would be Siwe::Message.verify which needs as arguments: the signature and then the message's domain, created_at and nonce.**

**Comment by w4ll3** [comment]
Hello @pabloruiz55, thanks for catching that. Would you mind confirming that #19 addresses your issue?

**Comment by pabloruiz55** [comment]
Hi, yes, it does. 
I had also submitted a PR to the examples repo with the fix:
[](https://github.com/spruceid/siwe-rails-examples/pull/4 )

**Comment by w4ll3** [comment]
@pabloruiz55 got it. I don't have access to approve that one, but I already reached out to the responsible. Thanks again!
