### ISSUE TITLE
SIWE.js Parity

### ISSUE THREAD

**Issue by w4ll3** [spruceid/siwe-ruby#2]
Points to achieve parity with `siwe`

- [x] basic message fields
- [x] message generation
- [ ] #3
- [x] regex parsing
- [x] message validation
- [ ] contract wallet util (might be a problem)

**Comment by q9f** [comment]
Could you walk me through (high level) what a contract wallet authentication looks like?

I could try to implement what's necessary for 1271.

https://github.com/q9f/eth.rb/issues/44
