### ISSUE TITLE
Upstream Blocker: MacOS support partially blocked by ruby-eth

### ISSUE THREAD

**Issue by bumblefudge** [spruceid/siwe-ruby#4]
See [this draft PR](https://github.com/se3000/ruby-eth/pull/43) for details -- revisit once that PR is merged

**Comment by q9f** [comment]
Hi, I already implemented Eth::Key fully without openssl dependency just using the secp256k1 gem. 

https://github.com/q9f/eth.rb/pull/4

The code is not yet released. I plan a major version bump for the eth gem once the rewrite is complete.

If you only use keys and personal_sign, you can give it a try already.

https://github.com/q9f/eth.rb/pull/24

**Comment by w4ll3** [comment]
As I mentioned in the discord would be cool to have an interface to interact with contract ABI so we can support Smart Contract wallets as well, but I understand that will take a little longer, so no worries. I'll give it a try and update the gem soon.

**Comment by q9f** [comment]
Wouldn’t the old ethereum.rb gem help with that?

https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/abi.rb

I was discussing this recently to merge the two gems.

**Comment by w4ll3** [comment]
If I remember correctly this gem was giving me some errors, I'll check that as well

**Comment by q9f** [comment]
Yes, both `ethereum` and `eth` gems are very outdated. That's why I started rewriting them in one place. If you can specify which features you exactly need, I can try to prioritize them. But I will also gladly accept pull requests :)

**Comment by q9f** [comment]
update: I implemented ABI 

https://github.com/q9f/eth.rb/pull/29

**Comment by wyc** [comment]
@q9f is this awesome! 👏 

I'm a huge fan of merging the two outdated gems into one, it's a great outcome for this repo to have only one Ethereum dependency. Thanks for your work!!

**Comment by q9f** [comment]
MacOS is fixed upstream

https://github.com/se3000/ruby-eth/releases/tag/v0.4.18
