### ISSUE TITLE
License as MIT and Apache 2.0

### ISSUE THREAD

**Issue by wyc** [spruceid/siwe-ruby#7]
The LICENSE and LICENSE.txt seem to both contain MIT. We should call them LICENSE-MIT and LICENSE-APACHE.

**Comment by q9f** [comment]
What would be the motivation to have two different permissive licenses? I tried some reading on the web and would still argue, having APACHE 2.0 does still cover all purposes without having additional benefits from an additional MIT license. Just curious if you discussed that. Usually (I thought), it would make sense to offer dual-licensing for permissive and viral licenses, i.e., APACHE 2.0 and GPL 3.0, so users can decide whether they want their stack to be viral or not.

**Comment by wyc** [comment]
My understanding is that MIT is just about a subset of Apache 2.0, the main difference being lack of patent provisions. However, one important edge case is compatibility with GPLv2, which you would get with MIT but not Apache 2.0. I wish I could explain more, but the legal nuances of license compatibility are likely beyond my understanding, so maybe someone more knowledgeable is able to chime in. Hope that helps as a start though!

https://www.apache.org/licenses/GPL-compatibility.html

**Comment by w4ll3** [comment]
#6
